START TRANSACTION;
UPDATE emp 
SET emp.SAL = emp.SAL*1.1;
SAVEPOINT p1;
DELETE FROM MY_EMPLOYEE;
SELECT count(*) FROM MY_EMPLOYEE;
ROLLBACK TO p1;
COMMIT;
SELECT count(*) FROM MY_EMPLOYEE;
SELECT empno, SAL from emp;
